version: '3'
services:
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
  api:
    build:
      dockerfile: Dockerfile
      context: ./
    image: wearable-api:latest
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379