spring.application.name: WearSensorAPI
spring.banner.image.location: classpath:static/REDS_Logo.png
spring.banner.image.width: 60
spring.banner.image.height: 40
spring.banner.image.pixelmode: BLOCK

server.servlet.context-path: /wearsensor
server.port: 8080

webclient:
  httpProperties:
    baseUrl: https://cloud.kaaiot.com/epts/api/v1/
    authUrl: https://authh.cloud.kaaiot.com/auth/realms/788e95cf-4520-4310-ac9d-feae22c4b279/protocol/openid-connect/token
  authProperties:
    grant_type: client_credentials
    client_id: 17800581-fad5-47d2-b19e-ecbd7ce87f00
    client_secret: 9fbec4eb-3c59-42f4-82fc-4667759902c3

mqtt:
  server: tcp://mqtt.cloud.kaaiot.com:1883
  clientId: WearSensorAPI
  connectionRetries: 3
  connectionTimeout: 30

kaaAppName: btngtro547tsntf25rtg
kaaAppVersion: v1

kaaMobileToken: mobile_1
kaaWatchToken: watch_1

base-repo: time-series/config
base-endpoint: applications/${kaaAppName}/time-series/data

kaaendpoints:
  endpoints:
    d291e666-f622-4ade-9a14-acbb6419ffd0:
      kp1/${kaaAppName}-${kaaAppVersion}/dcx/${kaaMobileToken}/json
    12b063b9-d51d-4d4f-a715-b7fbd244ad06:
      kp1/${kaaAppName}-${kaaAppVersion}/dcx/${kaaWatchToken}/json

springdoc:
  packages-to-scan: com.unimib.wearable.rest
spring:
  devtools:
    restart:
      enabled: true
  cache:
    type: redis

redis-host: localhost
redis-port: 6379
redis-ttl:
  cacheExpiration:
    applicationNames-cache: 60


resilience4j:
  circuitbreaker:
    configs:
      dataNameService:
        slidingWindowSize: 10
        slidingWindowType: TIME_BASED
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 1
    instances:
      mycircuitbreaker:
        baseConfig: dataNameService
        failureRateThreshold: 33
  timelimiter:
    instances:
      kaaServiceCB:
        timeoutDuration: 30s
        cancelRunningFuture: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
