spring.application.name: wearable-api
server.servlet.context-path: /middleware
server.port: 8080

webclient:
  httpProperties:
    baseUrl: https://cloud.kaaiot.com/epts/api/v1/
    authUrl: https://authh.cloud.kaaiot.com/auth/realms/788e95cf-4520-4310-ac9d-feae22c4b279/protocol/openid-connect/token
  authProperties:
    grant_type: client_credentials
    client_id: 17800581-fad5-47d2-b19e-ecbd7ce87f00
    client_secret: 9fbec4eb-3c59-42f4-82fc-4667759902c3

mqtt:
  server: tcp://mqtt.cloud.kaaiot.com:1883
  clientId: WearSensorAPI
  connectionRetries: 3
  connectionTimeout: 30

kaaAppName: btngtro547tsntf25rtg
kaaAppVersion: v1

kaaMobileToken: mobile_1
kaaWatchToken: watch_1

base-repo: time-series/config
base-endpoint: applications/${kaaAppName}/time-series/data

kaaendpoints:
  endpoints:
    d291e666-f622-4ade-9a14-acbb6419ffd0:
      kp1/${kaaAppName}-${kaaAppVersion}/dcx/${kaaMobileToken}/json
    12b063b9-d51d-4d4f-a715-b7fbd244ad06:
      kp1/${kaaAppName}-${kaaAppVersion}/dcx/${kaaWatchToken}/json

springdoc:
  packages-to-scan: com.unimib.wearable.rest
spring:
  devtools:
    restart:
      enabled: true
  cache:
    type: redis

redis-host: localhost
redis-port: 6379
time-to-live: 0 0/10 * * * *

resilience4j:
  circuitbreaker:
    instances:
      dataNameService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
