spring.application.name: wearable
server.servlet.context-path: /middleware
server.port: 8080

webclient:
  httpProperties:
    baseUrl: https://cloud.kaaiot.com/epts/api/v1/
  bearerToken: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJtQ2NXZFYtX005V2daaFRXVjBMS2twUm1OT1FkVnh6amExcUxaTnZGdGhZIn0.eyJqdGkiOiJmZWZmZmM2YS1kMTgwLTQ1YmQtYjA0YS1mZWZiNGU2YzlkOGQiLCJleHAiOjE2MjExMTIwMzgsIm5iZiI6MCwiaWF0IjoxNjE4NTIwMDM4LCJpc3MiOiJodHRwczovL2F1dGhoLmNsb3VkLmthYWlvdC5jb20vYXV0aC9yZWFsbXMvNzg4ZTk1Y2YtNDUyMC00MzEwLWFjOWQtZmVhZTIyYzRiMjc5IiwiYXVkIjoicmVhbG0tbWFuYWdlbWVudCIsInN1YiI6IjVjMjlmMmRjLTZkZmQtNDg2Zi04MDI2LWE2NzkwMWI5NDAwOSIsInR5cCI6IkJlYXJlciIsImF6cCI6IjE3ODAwNTgxLWZhZDUtNDdkMi1iMTllLWVjYmQ3Y2U4N2YwMCIsImF1dGhfdGltZSI6MCwic2Vzc2lvbl9zdGF0ZSI6ImE4NDdkNTg4LWVmZDctNDk5Yy05YTQ2LThhNzI4ZThkNjUzMiIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOltdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiYW5hbHl0aWNzLWFkbWluIiwidGVuYW50LWFkbWluIiwib2ZmbGluZV9hY2Nlc3MiLCJhbmFseXRpY3MtcmVhZGVyIiwidW1hX2F1dGhvcml6YXRpb24iLCJ0ZW5hbnQtcmVhZGVyIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsicmVhbG0tbWFuYWdlbWVudCI6eyJyb2xlcyI6WyJtYW5hZ2UtcmVhbG0iLCJtYW5hZ2UtaWRlbnRpdHktcHJvdmlkZXJzIiwibWFuYWdlLXVzZXJzIiwidmlldy1jbGllbnRzIiwicXVlcnktY2xpZW50cyJdfSwiMTc4MDA1ODEtZmFkNS00N2QyLWIxOWUtZWNiZDdjZTg3ZjAwIjp7InJvbGVzIjpbInVtYV9wcm90ZWN0aW9uIl19fSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwidGVuYW50X2lkIjoiNzg4ZTk1Y2YtNDUyMC00MzEwLWFjOWQtZmVhZTIyYzRiMjc5IiwiY2xpZW50SG9zdCI6IjE1MS4yMC4xNTMuMjA3IiwiY2xpZW50SWQiOiIxNzgwMDU4MS1mYWQ1LTQ3ZDItYjE5ZS1lY2JkN2NlODdmMDAiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInJvbGVzIjpbImFuYWx5dGljcy1hZG1pbiIsInRlbmFudC1hZG1pbiIsIm9mZmxpbmVfYWNjZXNzIiwiYW5hbHl0aWNzLXJlYWRlciIsInVtYV9hdXRob3JpemF0aW9uIiwidGVuYW50LXJlYWRlciJdLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzZXJ2aWNlLWFjY291bnQtMTc4MDA1ODEtZmFkNS00N2QyLWIxOWUtZWNiZDdjZTg3ZjAwIiwiY2xpZW50QWRkcmVzcyI6IjE1MS4yMC4xNTMuMjA3In0.NEKMGd_6zfxiahHBqW5YYkvqK63JP1-pHU6lwL64SVnAbOVIk2QOpR3PuEDlFNiLLkNBQBEg-3dL6yg3pCXmnDQd63f20MnNg8oxqAMCKhrgu5dN4RB6Ry9PLkCmFBk_0Cckw0Ij8e1pqjN-oq512EWq7p5cWro1cb94VeAIVliTKtyfxwTcRsgCwsV8MO4cZjj-QWHVtmfjFa3ii_DGX7Jlhb8xylp7ISJRV1J5Fe3M_jMemCHEyoJVl3GkEHLvOytMjD7l18JJSUbWP8Ecs_MvmN0HYANQD2Nf3x19aNiV_iScp7FCZdBL1LcyPPSiJ8-KqjKzF5S3S8vTKh9vyw
mqtt:
  server: tcp://mqtt.cloud.kaaiot.com:1883
  clientId: WearSensorAPI
  connectionRetries: 3
  connectionTimeout: 30

kaaAppName: btngtro547tsntf25rtg
kaaAppVersion: v1

kaaMobileToken: mobile_1
kaaWatchToken: watch_1

baseRepo: time-series/config
baseendpoint: applications/${kaaAppName}/time-series/data


kaaendpoints:
  endpoints:
    d291e666-f622-4ade-9a14-acbb6419ffd0:
      kp1/${kaaAppName}-${kaaAppVersion}/dcx/${kaaMobileToken}/json
    12b063b9-d51d-4d4f-a715-b7fbd244ad06:
      kp1/${kaaAppName}-${kaaAppVersion}/dcx/${kaaWatchToken}/json
springdoc:
  packages-to-scan: package com.unimib.wearable.rest
